parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Application/Kernel.php'

    App\Controller\:
        resource: '../src/Application/Controller/'
        tags: ['controller.service_arguments']

    App\Domain\Interfaces\Repository\GithubRepositoryInterface:
        class: App\Infrastructure\Repository\GithubApiRepository
        public: true
        arguments:
            - '@http_client'
            - '%env(GITHUB_API_TOKEN)%'
